import "./globals.css";
import type { Metadata } from "next";
import { Inter, JetBrains_Mono, DM_Sans, DM_Mono } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

const jetbrains_mono = JetBrains_Mono({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-jetbrains-mono",
});

const dm_sans = DM_Sans({
	subsets: ["latin"],
	display: "swap",
	weight: ["400", "500"],
	variable: "--font-dm-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.variable} ${jetbrains_mono.variable} ${dm_sans.variable}`}
			>
				{children}
			</body>
		</html>
	);
}
